-- ArchAI Database Connection Test Migration
-- Run this migration via Supabase dashboard or CLI to verify database access
-- Migration: 20260517000000_create_archai_connection_test_table.sql

-- Create a test table to verify write access to ArchAI database
create table if not exists public.archai_connection_test (
    id bigint generated by default as identity primary key,
    test_message text not null,
    tested_at timestamp with time zone default timezone('utc'::text, now()) not null,
    test_data jsonb default '{}'::jsonb
);

-- Comment on the table for clarity
comment on table public.archai_connection_test is 'Test table to verify ArchAI Supabase database connection';

-- Comments on columns
comment on column public.archai_connection_test.id is 'Primary key';
comment on column public.archai_connection_test.test_message is 'Test message indicating successful connection';
comment on column public.archai_connection_test.tested_at is 'Timestamp when the test was run';
comment on column public.archai_connection_test.test_data is 'Additional test data in JSON format';

-- Index for faster lookups (optional but good practice)
create index if not exists idx_archai_connection_test_tested_at on public.archai_connection_test(tested_at);

-- Insert a test record to verify write access
insert into public.archai_connection_test (test_message, test_data)
values (
    'ArchAI database connection verified via migration at ' || now(),
    jsonb_build_object(
        'test_type', 'connection_verification',
        'timestamp', now()::text,
        'project_ref', 'znizmdakncmrnowgwppu',
        'verified_by', 'Kilo AI Assistant'
    )
) on conflict do nothing; -- Prevent duplicate entries if run multiple times

-- Select the test record to confirm
select id, test_message, tested_at, test_data
from public.archai_connection_test
order by tested_at desc
limit 1;

-- Cleanup function (optional - uncomment if you want to automatically clean up)
-- delete from public.archai_connection_test where tested_at < now() - interval '1 hour';