-- Sessions table for storing capstone ideation sessions
-- Migration: 20260615000000_create_sessions_table.sql

create table if not exists public.sessions (
    id uuid generated by default as identity primary key,
    user_id uuid references auth.users not null,
    title text not null,
    conversation jsonb default '[]'::jsonb,
    blueprint text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.sessions enable row level security;

-- Create policies for authenticated users
create policy "Users can view their own sessions"
    on public.sessions for select
    using (auth.uid() = user_id);

create policy "Users can create their own sessions"
    on public.sessions for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own sessions"
    on public.sessions for update
    using (auth.uid() = user_id);

create policy "Users can delete their own sessions"
    on public.sessions for delete
    using (auth.uid() = user_id);

-- Index for faster queries
create index if not exists idx_sessions_user_id on public.sessions(user_id);
create index if not exists idx_sessions_created_at on public.sessions(created_at desc);